name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        uses: ./.github/actions/test
      - name: When Github action is given a basic input file
        uses: dlip/envy.sh@master
        with:
          input-file: tests/basic.env
      - name: Should set environment variables in the next step
        run: if [[ "$ENVIRONMENT" != "development" || "$VERSION" != "1.0.0" ]]; then exit 1; fi
      - name: When Github action is given a basic input file with output file
        uses: dlip/envy.sh@master
        with:
          input-file: tests/basic.env
          output-format: env-file
          output-file: action-output.env
      - name: Should write file
        run: if ! grep -q ENVIRONMENT=development action-output.env; then exit 1; fi
