name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        uses: ./.github/actions/test
      - name: Envy
        uses: dlip/envy.sh@master
        with:
          input-file: tests/basic.env
      - name: Test Envy action
        run: if [[ "$ENVIRONMENT" != "development" || "$VERSION" != "v1.0.0" ]]; then exit 1; fi
