name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        uses: ./.github/actions/test
        with:
          entrypoint: bash
          args: -e "cd tests && ./test.sh"