name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        uses: ./.github/actions/test
      - name: Envy
        uses: dlip/envy.sh
        with:
          file: tests/basic.env
      - name: Test Envy acion
        run: echo "$ENVIRONMENT=$VERSION"
